on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: latest
      - uses: mymindstorm/setup-emsdk@v14
      - run: emcc -v
      - run: whereis emcc
      - run: pwd
      - run: ls -lash
      - run: zig build
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: BioMechanics
          path: zig-out/
