on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build binaries
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: latest
      - run: zig build -Dtarget=x86_64-windows -Doptimize=ReleaseFast
      - run: zig build -Doptimize=ReleaseFast
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: BioMechanics
          path: zig-out/bin
