on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build binaries
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: latest
      - run: zig build -Dtarget=x86_64-windows -Doptimize=ReleaseFast
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev libxfixes-dev libwayland-bin
          version: 1.0
      - run: zig build -Doptimize=ReleaseFast
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: BioMechanics
          path: zig-out/bin
