on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libwayland-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libxkbcommon-dev libxfixes-dev
          version: 1.0
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.50
          actions-cache-folder: "emsdk-cache"
      - run: zig build -Dtarget=wasm32-emscripten -Doptimize=ReleaseFast --sysroot "$EMSDK/upstream/emscripten"
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: zig-out/htmlout/

      - uses: actions/upload-artifact@v4.6.0
        with:
          name: BioMechanics
          path: zig-out/

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
